### ISSUE TITLE
XmlBuilder is not thread safe

### ISSUE THREAD

**Issue by 12266601032** [SimY4/xpath-to-xml#5]
com.github.simy4.xpath.XmlBuilder{
   private static final Iterable<NavigatorSpi> navigatorSpis = ServiceLoader.load(NavigatorSpi.class);
}

ServiceLoader is not thread safe
![image](https://user-images.githubusercontent.com/22188742/58377691-dd003880-7fb8-11e9-8844-30f6af84429c.png)

**Comment by 12266601032** [comment]
java.util.NoSuchElementException: null
	at sun.misc.CompoundEnumeration.nextElement(CompoundEnumeration.java:59) ~[na:1.8.0_181]
	at java.util.ServiceLoader$LazyIterator.hasNextService(ServiceLoader.java:357) ~[na:1.8.0_181]
	at java.util.ServiceLoader$LazyIterator.hasNext(ServiceLoader.java:393) ~[na:1.8.0_181]
	at java.util.ServiceLoader$1.hasNext(ServiceLoader.java:474) ~[na:1.8.0_181]
	at com.github.simy4.xpath.XmlBuilder.build(XmlBuilder.java:188) ~[xpath-to-xml-core-2.1.0.jar:2.1.0]
